project:
  type: website

website:
  title: "JS Playground"
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CheatSheet
      - href: js_map.qmd
        text: JS Concepts
      - href: play_js.qmd
        text: JS Sandbox

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css # Puedes seleccionar w3.css para otros estilos
    toc: true


